components: qcquickie
grid: none
group: ''
init_only: false
md5skip: false
memory: 10
partition: standard
priority_mapping:
  high: outbreak
  low: daytime
read_pattern: (?P<sample_name>.+?)(?P<sample_number>(_S[0-9]+)?)(?P<lane>(_L[0-9]+)?)_(?P<paired_read_number>R[1|2])(?P<set_number>(_[0-9]+)?)(?P<file_extension>\.fastq\.gz)
restart_times: 2
sample_folder: samples
sample_sheet: sample_sheet.xlsx
samples_to_ignore:
- Undetermined
samplesheet_column_mapping:
  Comments: Comments
  emails: Initials
  group: SupplyingLab
  priority: Priority
  provided_species: Organism
  run_name: ExperimentName
  sample_name: SampleID
threads: 4
tmp_dir: /Users/stefanocardinale/tmp
type: project
unlock: false
use_mongodb: true
walltime: 03:00:00
)_(?P<paired_read_number>R[1|2])(?P<set_number>(_[0-9]+)?)(?P<file_extension>\.fastq\.gz)
samples_to_ignore: ["Undetermined"]
# samples_to_include: null
memory: &memory 10 #in Gb
threads: &threads 4
restart_times: 2
init_only: False # initialize samples but don't run the components
unlock: False # Run the components' snakemake in unlock mode (components wont run but will unlock directories)
md5skip: False # set to True to skip md5sum update when recreating samples. Recommended: False
tmp_dir: "/Users/stefanocardinale/tmp" # Run compute intensive steps on a scratch dir to avoid overdoing IO

# --Optional override values--
# run_name: NAME                              # if provided use that for db if not use folder

# For processing sample sheets
samplesheet_column_mapping:
  sample_name: "SampleID"
  group: "SupplyingLab" 
  emails: "Initials"
  run_name: "ExperimentName"
  priority: "Priority"
  provided_species: "Organism" # a required name
  Comments: "Comments"

priority_mapping:
  high: "outbreak"
  low: "daytime"
