#-Information---------------------------------------------------------------------------------------
name: min_read_check
version: 1.0
target: sample
type: pipeline
recommendation: recommended
description: >
  Checks that there's a minimum number of reads after trimming to run.
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
min_num_reads: 10000
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
adapters_fasta: "resources/adapters.fasta"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    reads:
      R1:
      R2:
#-DB Value changes (excluding component output)-----------------------------------------------------
# None
#---------------------------------------------------------------------------------------------------
